apiVersion: v1
kind: Pod
metadata:
  name: secure-pod-1
  namespace: audit-zone
spec:
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: nginx
      image: nginx:alpine
      securityContext:
        privileged: false  # Явно отключаем privileged
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]